export const projects = [
  {
    id: 1,
    name: "FreshUI",
    description:
      "FreshUI is a Component Library developed using plain HTML, CSS and Javascript",
    tech: "HTML, CSS, Javascript",
    features: [
      "Alerts",
      "Card",
      "Buttons",
      "Grid Layout",
      "Image",
      "Snackbar",
      "Avatar",
      "Badge",
      "Input",
      "Navigation",
      "Chip",
      "Typography",
      "Rating",
      "Modal",
      "Lists",
      "Slider",
    ],
    image: "images/FreshUI.png",
    source: "",
    project: "",
  },
  {
    id: 2,
    name: "FreshBuy",
    description: "Ecommerce website",
    tech: "HTML, CSS, Javascript, ReactJS, Context",
    features: ["Authentication", "Cart", "Wishlist", "Payment"],
    image: "images/FreshBuy.png",
    source: "",
    project: "",
  },
  {
    id: 3,
    name: "FreshView",
    description: "Video Library",
    tech: "HTML, CSS, Javascript, ReactJS, Context",
    features: ["Authentication", "Playlist", "Wishlist", "Liked"],
    image: "images/FreshView.png",
    source: "",
    project: "",
  },
  {
    id: 4,
    name: "FreshUI",
    description:
      "FreshUI is a Component Library developed using plain HTML, CSS and Javascript",
    tech: "HTML, CSS, Javascript",
    features: [
      "Alerts",
      "Card",
      "Buttons",
      "Grid Layout",
      "Image",
      "Snackbar",
      "Avatar",
      "Badge",
      "Input",
      "Navigation",
      "Chip",
      "Typography",
      "Rating",
      "Modal",
      "Lists",
      "Slider",
    ],
    image: "images/FreshUI.png",
    source: "",
    project: "",
  },
  {
    id: 5,
    name: "FreshBuy",
    description: "Ecommerce website",
    tech: "HTML, CSS, Javascript, ReactJS, Context",
    features: ["Authentication", "Cart", "Wishlist", "Payment"],
    image: "images/FreshBuy.png",
    source: "",
    project: "",
  },
  {
    id: 6,
    name: "FreshView",
    description: "Video Library",
    tech: "HTML, CSS, Javascript, ReactJS, Context",
    features: ["Authentication", "Playlist", "Wishlist", "Liked"],
    image: "images/FreshView.png",
    source: "",
    project: "",
  },
  {
    id: 7,
    name: "FreshUI",
    description:
      "FreshUI is a Component Library developed using plain HTML, CSS and Javascript",
    tech: "HTML, CSS, Javascript",
    features: [
      "Alerts",
      "Card",
      "Buttons",
      "Grid Layout",
      "Image",
      "Snackbar",
      "Avatar",
      "Badge",
      "Input",
      "Navigation",
      "Chip",
      "Typography",
      "Rating",
      "Modal",
      "Lists",
      "Slider",
    ],
    image: "images/FreshUI.png",
    source: "",
    project: "",
  },
  {
    id: 8,
    name: "FreshBuy",
    description: "Ecommerce website",
    tech: "HTML, CSS, Javascript, ReactJS, Context",
    features: ["Authentication", "Cart", "Wishlist", "Payment"],
    image: "images/FreshBuy.png",
    source: "",
    project: "",
  },
  {
    id: 9,
    name: "FreshView",
    description: "Video Library",
    tech: "HTML, CSS, Javascript, ReactJS, Context",
    features: ["Authentication", "Playlist", "Wishlist", "Liked"],
    image: "images/FreshView.png",
    source: "",
    project: "",
  },
];
